export const GET_ALL_QUESTIONS = 'GET_ALL_QUESTIONS';
export const GET_ALL_QUESTIONS_LOAD = 'GET_ALL_QUESTIONS_LOAD';
export const GET_ALL_QUESTIONS_SUCCESS = 'GET_ALL_QUESTIONS_SUCCESS';
export const GET_ALL_QUESTIONS_FAIL = 'GET_ALL_QUESTIONS_FAIL';

export const SUBMIT_ANSWER = 'SUBMIT_ANSWER';
export const SUBMIT_ANSWER_LOAD = 'SUBMIT_ANSWER_LOAD';
export const SUBMIT_ANSWER_SUCCESS = 'SUBMIT_ANSWER_SUCCESS';
export const SUBMIT_ANSWER_FAIL = 'SUBMIT_ANSWER_FAIL';
